services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    # build: spark/
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8082:8080
      - 10000:10000
      - 10001:10001
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
    volumes:
      - ./warehouse:/warehouse
  trino:
    image: trinodb/trino:435
    container_name: trino
    networks:
      iceberg_net:
    ports:
      - "8083:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./warehouse:/warehouse 
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1 
  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    networks:
      iceberg_net:
    environment:
      - SERVICE_NAME=metastore
      - SKIP_SCHEMA_INIT=true
    ports:
      - "9083:9083"
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
  # ---------- N8N ----------
  n8n:
    image: n8nio/n8n
    container_name: n8n
    networks:
      iceberg_net:
    ports:
      - "5678:5678"
# ---------- DBT ----------
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt
    networks:
      iceberg_net:
    depends_on:
      - trino
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app

  # ---------- AIRFLOW DB ----------
  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    networks:
      iceberg_net:
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  # ---------- AIRFLOW INIT ----------
  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow-init
    depends_on:
      - airflow-postgres
    networks:
      iceberg_net:
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "airflow-secret"
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@admin.com"

  # ---------- AIRFLOW WEBSERVER ----------
  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      iceberg_net:
    ports:
      - "8080:8080"
    environment:
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/2afc0f63-bfb4-45ff-83c9-6b4389b1e6c0
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "airflow-secret"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    command: webserver

  # ---------- AIRFLOW SCHEDULER ----------
  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    networks:
      iceberg_net:
    environment:
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/2afc0f63-bfb4-45ff-83c9-6b4389b1e6c0
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "airflow-secret"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
  
networks:
  iceberg_net: